spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev?serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true